language: ruby
rvm:
- 2.2.3
deploy:
  provider: heroku
  app: scomo
  api_key:
    secure: WfwPQ2uAmgV1MtC3KEZydTUJdfFazf627TVMiqAeC+esMsSEZpbEWWkSESqffjCQzE5MvwAk/4zAid6xL99KI4+hvA8LWArjSXPAkjs0wtzuhefCvnHJ000djhi4tRb0QY+LD0xCEejUXrUXNk8EOfvSsxYd6nqnBGC5lCTY5IzXqIOzV6GxxApVlDQstVGkLU7/ggRKYP0ir249a+p9hJWDQcra4Jn9+9EQM4h1V7pP/DtTdt5CRHcuwHLNPfLAooRa0DMTF+7TVytMPHxBy3SCZjjJGiA9K3JFF6FSu/RNcCvSnzGb3iy1QocTPMIqGgJdJ1f6YJpudpwPvin5OZSUIxp6wG+vhotA+nOyY/KtO3uPjHuvnx5S4aUcJ9eaf3kTUdA2pnJ9oKDPM6ggdbJDQmOcdpvASawVealDukodJBsKBT14kq3bGpOG67HhGc+IJ3RJzwyKEp4A80Ra5eQT6g/Mg4ztfDFifjUeOUHeXhCg82Gt19FxcNN2LU67g412BeAZXm5YvmuBsC9j/Vhe6cqFggF0G3mhyD8uDF6nRLxNFQmH24/ZXFVg/sE93pFkB98QKntXWcnYwKrIAS8xQddHeIGyF9JNCLT1Sb4UtF3nF/0GI9pfH82ug8QR33Squ0W79CNqhPHcH8vMgvdZkuWxD54eYevCUnHqE0A=

after_success:
  - coveralls